### ISSUE TITLE
Add package with Trust helper functions

### ISSUE THREAD

**Issue by dpereskokov** [trustwallet/web-core#103]

**Comment by dpereskokov** [comment]
create package and Implement `coinToAddress(coin: CoinType) => string` method

**Comment by leoneparise** [comment]
Do we need a new package for it?

**Comment by dpereskokov** [comment]
Yes, the service in rpc package is for calling api functions. The package is for Trust related helper functions etc. They may be used outside of rpc package.

**Comment by dpereskokov** [comment]
In fact we can even merge Types package with this one. As I understand all coin codes there are Trust related.

**Comment by vikmeup** [comment]
`Types` is independent package - nothing to do with trust wallet, it could be just coin types for any blockchain.

```
coinToAddress()
tokentToAddress()
```

this two methods specific to api or trust-api package.

**Comment by leoneparise** [comment]
I agree. I already added those into `api` package. We don't need a helper package for now. Closing the issue.
