### ISSUE TITLE
Create BitcoinRPCService

### ISSUE THREAD

**Issue by leoneparise** [trustwallet/web-core#56]
Add RPCService package. The first RPCService to get supported is Bitcoin.

This involves:

- Create a new package
- Setup typescript, eslint, jest, .env variables and node scripts
- Add BitcoinRPCService
- Add Tests

Methods:
 - getLatestBlock(),
 - getBalance(xpub: string),
 - listUnspent(xpub: string),
 - listTransactions(address: string),
 - getTransactionDetail(hash: string),
 - estimateFee(priority: int),
 - broadcastTransaction(data: string),

The RPC should map blockbook calls: https://github.com/trezor/blockbook

**Comment by dpereskokov** [comment]
#57

**Comment by leoneparise** [comment]
PR: https://github.com/trustwallet/web-core/pull/57

**Comment by leoneparise** [comment]
Fixed in PR #57.
