### ISSUE TITLE
Create EthereumRPCService

### ISSUE THREAD

**Issue by wpank** [trustwallet/web-core#59]
Add Ethereum to RPCService. 

At minimum, the EthereumRPC service will need to implement the following functions:

- `loadGasPrice()`

- `estimateNonce(address)`

- `getAllTokenBalances(assets)`

- `getAccountBalance(asset)`

- `estimateGasLimit(from, to, amount, gasPrice, payloadData)`

- `broadcastTransaction(signedTx)`

- `async getBlockHeight()`

**Comment by dpereskokov** [comment]
#77
