### ISSUE TITLE
Cosmos signed tx returns invalid JSON

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/web-core#92]
Try to sign Cosmos Tx from 

https://github.com/trustwallet/web-core/blob/master/packages/example/src/ProviderExamples.tsx

You will get something like:

`{"json":"{"mode":"block","tx":{"fee":{"amount":[{"amount":"5000","denom":"uatom"}],"gas":"200000"},"memo":"","msg":[{"type":"cosmos-sdk/MsgDelegate","value":{"amount":{"amount":"1","denom":"uatom"},"delegator_address":"cosmos1et7a8svmxfkz23mn280k34q6upj36d7lggflpa","validator_address":"cosmosvaloper102ruvpv2srmunfffxavttxnhezln6fnc54at8c"}}],"signatures":[{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"Ai7wK1m8FTfBSoiFKXOfXC6W9Ia/nCXOKMiZ6pnzpvcK"},"signature":"VhliQhv5XMqmlO0qhv8i7FC71782Yk0yGJ5aJY01WfFS61TunhHOe9vkE8pnVg5KPiAtRkwLNGwyOvwiL7DP6w=="}],"type":"auth/StdTx"}}"}`

To have a correct JSON it must be:

`{"json":{"mode":"block","tx":{"fee":{"amount":[{"amount":"5000","denom":"uatom"}],"gas":"200000"},"memo":"","msg":[{"type":"cosmos-sdk/MsgDelegate","value":{"amount":{"amount":"1","denom":"uatom"},"delegator_address":"cosmos1et7a8svmxfkz23mn280k34q6upj36d7lggflpa","validator_address":"cosmosvaloper102ruvpv2srmunfffxavttxnhezln6fnc54at8c"}}],"signatures":[{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"Ai7wK1m8FTfBSoiFKXOfXC6W9Ia/nCXOKMiZ6pnzpvcK"},"signature":"VhliQhv5XMqmlO0qhv8i7FC71782Yk0yGJ5aJY01WfFS61TunhHOe9vkE8pnVg5KPiAtRkwLNGwyOvwiL7DP6w=="}],"type":"auth/StdTx"}}}`

We found it during platform developing (@artall64 & @enorage)

**Comment by leoneparise** [comment]
This issue was fixed in this PR wallet-core project a while ago: https://github.com/trustwallet/wallet-core/pull/574

What iOS version are you using?

**Comment by EnoRage** [comment]
I am using 2.6905.0.
Here is the demo
![demo](https://user-images.githubusercontent.com/22479658/63991124-306daf80-caef-11e9-845d-6762d12c47c2.gif)

**Comment by vikmeup** [comment]
Fixed in the latest iOS build
